# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ecg.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ecg.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tecg.proto\x12\tecgstream\"T\n\x07\x45\x43GData\x12\x0e\n\x06values\x18\x01 \x03(\x01\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x13\n\x0bsample_rate\x18\x04 \x01(\x05\"b\n\x0f\x41rrhythmiaAlert\x12\x17\n\x0f\x61rrhythmia_type\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x32M\n\nECGService\x12?\n\tStreamECG\x12\x12.ecgstream.ECGData\x1a\x1a.ecgstream.ArrhythmiaAlert(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ecg_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ECGDATA']._serialized_start=24
  _globals['_ECGDATA']._serialized_end=108
  _globals['_ARRHYTHMIAALERT']._serialized_start=110
  _globals['_ARRHYTHMIAALERT']._serialized_end=208
  _globals['_ECGSERVICE']._serialized_start=210
  _globals['_ECGSERVICE']._serialized_end=287
# @@protoc_insertion_point(module_scope)
