# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_gen import ecg_pb2 as ecg__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ecg_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ECGServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamECG = channel.stream_stream(
                '/ecgstream.ECGService/StreamECG',
                request_serializer=ecg__pb2.ECGData.SerializeToString,
                response_deserializer=ecg__pb2.ArrhythmiaAlert.FromString,
                _registered_method=True)


class ECGServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamECG(self, request_iterator, context):
        """Bi-directional stream: Client sends ECGData, Server sends ArrhythmiaAlerts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ECGServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamECG': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamECG,
                    request_deserializer=ecg__pb2.ECGData.FromString,
                    response_serializer=ecg__pb2.ArrhythmiaAlert.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ecgstream.ECGService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ecgstream.ECGService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ECGService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamECG(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ecgstream.ECGService/StreamECG',
            ecg__pb2.ECGData.SerializeToString,
            ecg__pb2.ArrhythmiaAlert.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
